version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env  # <-- Ye line change ki hai taaki root folder se .env utha le

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend